### ISSUE TITLE
Being able to listen to pageChange event.

### ISSUE THREAD

**Issue by LeenaMansour** [prolificinteractive/ParallaxPager#10]
There isn't currently a straightforward way to allow for tracking the pageChange event.
For example, if I have 3 pages scrolling through using ParallaxPager, and I want some images to change or animation to happen once the user scrolls to the 3rd page. Since ParallaxContainer is the pageChangeEventListener and does not allow for setting a new one, it seems the only solution would be to subclass PrallaxContainer.

Is it possible to attach a pageChangeListener to ParallaxContainer instead?

Thanks!

**Comment by dandc87** [comment]
Release 2.1.0 should be up on Maven Central shortly with a fix for this
