### ISSUE TITLE
Not respecting visibility from layout file

### ISSUE THREAD

**Issue by LeenaMansour** [prolificinteractive/ParallaxPager#12]
All components of the layout file are always visible, even if their visibility was set to invisible/gone. I'm performing some animations once the page is scrolled that require some components to not be visible.

This is because of the code in ParallaxContainer in onPageScrolled sets the visibility to VISIBLE when the page is on the screen, and GONE when it's off the screen.

I suggest only changing visibility if the layout hasn't set it to INVISIBLE, but I'm not sure if that would be too obscure for future users of your library. I can put a PR up doing that if you agree.

Thanks!

**Comment by mluedke2** [comment]
So @dandc87 and I think the way to do this is to make a new view attribute that will mark that view as one that will override visibility. `onPageScrolled` won't do anything to the visibility of any views marked with that attribute, and then you can implement your own listener to manipulate the visibility manually.

**Comment by vinc3m1** [comment]
Why can't you just read `android:visibility` instead of making a new attribute? If that value is set, assume it's a user override.

**Comment by mluedke2** [comment]
Using `android:visibility` like that would work for this issue, but I feel like it's more explicit to have a custom attribute specifically for overriding visibility.
