### ISSUE TITLE
A factory has already been set on this LayoutInflater

### ISSUE THREAD

**Issue by ErikKarlsson** [prolificinteractive/ParallaxPager#18]
I ran into this issue and saw that it was fixed in one of the more recent commits: 
https://github.com/prolificinteractive/ParallaxPager/commit/a3829d9443de78169e0d94a29a7f2e7d3987f663

Will the version on Maven Central be updated with this fix?

Thanks!

**Comment by dandc87** [comment]
Sorry, releasing that slipped my mind :disappointed: 

Should be out as 2.2.1 now
