### ISSUE TITLE
views disappear

### ISSUE THREAD

**Issue by qstuff** [prolificinteractive/ParallaxPager#19]
hi, i tried out your lib, looked like it's exactly what i need. faced the problem that all views disappear after scrolling has finished, only the last view i added in setupChildren() remains visible. any hints on this ?
using 2.2.1 and followed exactly the example

**Comment by programmingnatp** [comment]
Hi and thank you for your interest in our project! We are closing out the issue for now because we are unable to replicate. But feel re-submit an issue if you feel the problem still persists, and please also include steps to replicate. Thanks again.
