### ISSUE TITLE
Support for sdk 21?

### ISSUE THREAD

**Issue by LeenaMansour** [prolificinteractive/ParallaxPager#7]
When I change the target version in the example module to 21, everything breaks. Is this because the library does not support it, or is it just the example app?

**Comment by mluedke2** [comment]
Thank you for finding this out. Right now it seems that the library doesn't support SDK version 21. Sorry about that! It seems to be something with the way views are inflating. I will continue looking into it and close this once I have it fixed.

**Comment by LeenaMansour** [comment]
great thank you!

**Comment by vinc3m1** [comment]
@mluedke2 there are some updates to how a custom LayoutInflater should be made in Lollipop, see http://chrisjenx.com/calligraphy-2-0-0/

**Comment by mluedke2** [comment]
thanks @vinc3m1, that looks exactly like the issue here.

**Comment by dandc87** [comment]
Have working implementation for on v21 up on `bugfix/api-21-error`. Though it doesn't seem to work when using the appcompat support library.

**Comment by mluedke2** [comment]
This should now be fixed with #9 . Thank you!

**Comment by mluedke2** [comment]
the update to maven central is forthcoming
