### ISSUE TITLE
Out of Memory Issues.

### ISSUE THREAD

**Issue by muthuprabhu-kp** [prolificinteractive/ParallaxPager#8]
in Some of the device I am getting Out of Memory and the app closes. is there is a way to fix this?

**Comment by dandc87** [comment]
Could you post the stack-trace and some of your code to help debug this?

**Comment by programmingnatp** [comment]
Hi and thank you for your interest in our project. As we are unable to replicate the issue,  the issue will be closed. But please feel free to re-submit the issue if you feel it still occurs. Should you resubmit the the issue, please also include steps to reproduce, including the device and Android version you are using. Thanks again!
